### ISSUE TITLE
[1, 1, 1] signal is not working

### ISSUE THREAD

**Issue by afanasy** [vail-systems/node-fft#1]
```js
> console.log(fft([1,1,1]))
TypeError: Cannot read property '0' of undefined
    at Object.complexMultiply [as multiply] (/Users/afanasy/fft/node_modules/fft-js/src/complex.js:24:22)
```

**Comment by nevosegal** [comment]
@afanasy, the Cooley-Tukey radix-2 algorithm (which is the one implemented here) _requires_ the input signal to have a length of a power of two. Try using signals with length 2^1, 2^2, 2^3,...,2^k.

**Comment by afanasy** [comment]
Thanks @nevosegal I'll try it
